name: Feature request
description: Suggest an idea for Chord
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "I want to ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like Chord to do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds you considered
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
